### ISSUE TITLE
请问是否方便给 repo 加一个 License

### ISSUE THREAD

**Issue by Orenoid** [anrgct/utools-xunfei-ocr#16]
个人打算基于该仓库的代码，稍微扩展下功能，写个定制的小工具，刚好这个插件的现有功能跟我的需求契合度比较高。
不过由于项目中目前没有任何 License，我不能直接在这上面做改动，希望能行个方便，谢谢。

**Comment by anrgct** [comment]
没想好呢, 这些界面的东西没什么, 但是接口是个收费资源, 不能滥用

**Comment by Orenoid** [comment]
目前代码内好像不包含 app_key ？应该不会涉及到讯飞那边 APP 的收费额度。不过总的来讲我只是想复用一下界面代码，讯飞那边我已经申请了自己的 APP 了

**Comment by anrgct** [comment]
界面没问题，就测试服务那里有问题，你修改了用自己的app key是可以的

**Comment by Orenoid** [comment]
好的，非常感谢
