### ISSUE TITLE
请问是否愿意更换印刷文字识别（多语种）使用的API

### ISSUE THREAD

**Issue by Wolfsin** [anrgct/utools-xunfei-ocr#20]
你好，我经常使用你开发的插件，最近因为测试服务的调用次数问题，好像已经无法正常使用。因此我决定切换至自己的接口。
我注意到你目前使用的是讯飞的[印刷文字识别（多语种）intsig]这个API，但是相同的功能，讯飞最近提供了新的[印刷文字识别（多语种）]API，我询问客服，这个新的API允许注册用户，每日调用500次（免费额度），我想可以解决目前接口次数不足的问题。
但是我对前端并不是很熟悉，我尝试clone你的代码，并使用utools的开发工具进行了导入，但是没有办法正常的跑起来。
而且新的API变更了新的认证方式。我不太清楚应该修改哪一部分，如果能告诉我修改的部分，或者你愿意在下一个版本更改成这个新接口就好了。
新API文档：https://www.xfyun.cn/services/xf-printed-word-recognition

**Comment by anrgct** [comment]
intsig是后面新出的，用的一直是不带intsig的，你直接把你的app key填到自定义里就可以用了吧

**Comment by Wolfsin** [comment]
> intsig是后面新出的，用的一直是不带intsig的，你直接把你的app key填到自定义里就可以用了吧

intsig是之前的，控制面板里面的服务接口认证信息是APPID和APIKey，新的这个，控制面板里面的服务接口认证信息是APPID，APISecret和APIKey。
而且我看了一下代码里面的接口信息，新接口的地址是http(s)://api.xf-yun.com/v1/private/s00b65163；而代码里面的是intsig的接口地址
[![f4YfYT.png](https://z3.ax1x.com/2021/08/17/f4YfYT.png)](https://imgtu.com/i/f4YfYT)

**Comment by anrgct** [comment]
我看到啦，唯独多语言的接口变了，赠送额度的换了新api，我等下个版本一起修复吧

**Comment by Wolfsin** [comment]
好的，坐等新版本

**Comment by anrgct** [comment]
今天咨询了讯飞客服，印刷文字识别（多语种）beta是测试版本，不能充值，目前仅支持中、英、日、韩、俄。印刷文字识别（多语种）intsig是正式版本，可以充值，支持中文（简体、繁体)、英、日、韩、德、法、意、葡、西、荷多种语言文字识别。

**Comment by Wolfsin** [comment]
> 今天咨询了讯飞客服，印刷文字识别（多语种）beta是测试版本，不能充值，目前仅支持中、英、日、韩、俄。印刷文字识别（多语种）intsig是正式版本，可以充值，支持中文（简体、繁体)、英、日、韩、德、法、意、葡、西、荷多种语言文字识别。

虽然是测试版，但是每天每人500的额度还是很吸引人的。如果不打算更换接口，可以考虑加入新的接口吗？或者不知道能不能给我一点开发的提示。我尝试clone你的代码，但是没办法进行调试，开发工具提示main不存在。
我也试过`npm install`，但是会报错，导致之后的build也无法正常进行。

**Comment by anrgct** [comment]
我下个更新会加上的，不过后面不开源了，涉及收费内容
