### ISSUE TITLE
mac截图识别

### ISSUE THREAD

**Issue by ynzy** [anrgct/utools-xunfei-ocr#9]
mac截图自动识别时，不管打开什么窗口，都只能截取桌面的窗口，无法进行文字识别

**Comment by anrgct** [comment]
我的macos 10.14.6是正常的，截图调用的是tools的“截图”功能，你可以试试直接在utools输入框输入“截图”使用后看截图正不正常，不正常的话你把系统环境等报一下，然后我反馈给tools官方
